spring.application.name=courseworkLuchanetskyi

# Datasource configuration
spring.datasource.url=jdbc:postgresql://dpg-d3na3p9r0fns73fevm9g-a/lab2lol
spring.datasource.username=user
spring.datasource.password=qtIkrCUVuURsivpoYGU3ZDIX8Q8PMgzp
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# JWT
jwt.secret=${JWT_SECRET:eyJzZWNyZXRfa2V5X3dpdGhfMzJfY2hhcnN9dsu7fHSF7sachSFbjkANCedsjfvbs9734hf73nf37asjdc6sefhv634}
jwt.expiration=${JWT_EXPIRATION:86400000}

# Swagger/OpenAPI
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui
